### ISSUE TITLE
Test fail on CI/CD

### ISSUE THREAD

**Issue by alexandru0-dev** [Vrtgs/thirtyfour#7]
Github Action test workflow fails as cannot connect to the browser instance.

**Comment by Vrtgs** [comment]
yeah, ik I mentioned that

**Comment by alexandru0-dev** [comment]
I've created the issue moments before reading your comment, also this allow to track it.
Do you have any clue of why they could fail to connect?
Could it be that the webdriver proxy takes a little more time to initialize then when the `cargo test` is run?

**Comment by Vrtgs** [comment]
the driver just starts on a different port for some reason

**Comment by alexandru0-dev** [comment]
Ok that was unexpected
Nice work
